# Generated by Django 6.0.6 on 2026-07-07 07:12

import apps.core.models
import apps.inventory.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('checkout', '0001_initial'),
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='packages',
            fields=[
                ('id', models.CharField(default=apps.core.models.generate_id, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package_name', models.CharField(max_length=255)),
                ('packaging_charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('container_type', models.CharField(choices=[('box', 'Box'), ('bag', 'Bag'), ('envelope', 'Envelope'), ('other', 'Other')], max_length=100)),
                ('length', models.DecimalField(decimal_places=2, max_digits=10)),
                ('breadth', models.DecimalField(decimal_places=2, max_digits=10)),
                ('height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dimension_unit', models.CharField(choices=[('cm', 'Centimeters'), ('m', 'Meters'), ('in', 'Inches'), ('ft', 'Feet')], max_length=100)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight_unit', models.CharField(choices=[('kg', 'Kilograms'), ('g', 'Grams'), ('lb', 'Pounds'), ('oz', 'Ounces')], max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('id', models.CharField(default=apps.core.models.generate_id, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_quantity', models.PositiveIntegerField(default=0)),
                ('reserved_quantity', models.PositiveIntegerField(default=0)),
                ('low_stock_threshold', models.PositiveIntegerField(default=0)),
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='catalog.product_variants')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='inventory_reservation',
            fields=[
                ('id', models.CharField(default=apps.core.models.generate_id, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(default=apps.inventory.models.reservation_expiry)),
                ('status', models.CharField(choices=[('active', 'Active'), ('confirmed', 'Confirmed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=30)),
                ('cart_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_reservation', to='checkout.shopping_carts')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_reservation', to='identity.user_profiles')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_reservation', to='catalog.product_variants')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
