# Generated by Django 6.0.6 on 2026-07-07 07:12

import apps.core.models
import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_attributes',
            fields=[
                ('id', models.CharField(default=apps.core.models.generate_id, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('display_label', models.CharField(max_length=100)),
                ('input_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('alphanumeric', 'Alphanumeric'), ('colour', 'Color')], max_length=100)),
                ('attribute_name', models.CharField(max_length=100)),
                ('attribute_value', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='product_variants',
            fields=[
                ('id', models.CharField(default=apps.core.models.generate_id, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('variant_title', models.CharField(max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='variant_title', unique=True)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('serial_number', models.CharField(blank=True, max_length=80, null=True)),
                ('variant_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_status', models.CharField(choices=[('in_stock', 'In Stock'), ('out_of_stock', 'Out of Stock'), ('pre_order', 'Pre Order')], max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('attributes', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.CharField(default=apps.core.models.generate_id, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_title', models.CharField(max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='product_title', unique=True)),
                ('product_description', models.TextField()),
                ('style_code', models.CharField(max_length=100)),
                ('listing_status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], max_length=100)),
                ('product_mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hsn_code', models.CharField(max_length=100)),
                ('search_keywords', models.TextField()),
                ('attributes', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.CharField(default=apps.core.models.generate_id, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name', unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/')),
                ('is_active', models.BooleanField(default=True)),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.categories')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='product_images',
            fields=[
                ('id', models.CharField(default=apps.core.models.generate_id, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('media_asset_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='core.media_assets')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='product_reviews',
            fields=[
                ('id', models.CharField(default=apps.core.models.generate_id, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rating', models.PositiveIntegerField()),
                ('review_text', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='identity.user_profiles')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
