# Generated by Django 6.0.6 on 2026-07-07 07:12

import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='coupons',
            fields=[
                ('id', models.CharField(default=apps.core.models.generate_id, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coupon_code', models.CharField(max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('applies_to', models.CharField(choices=[('all_products', 'All Products'), ('specific_products', 'Specific Products'), ('specific_categories', 'Specific Categories'), ('specific_users', 'Specific Users'), ('specific_user_groups', 'Specific User Groups'), ('specific_payment_methods', 'Specific Payment Methods'), ('specific_shipping_methods', 'Specific Shipping Methods')], max_length=100)),
                ('applicable_items', models.JSONField(blank=True, null=True)),
                ('min_order_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_discount_cap', models.DecimalField(decimal_places=2, max_digits=10)),
                ('can_be_combined', models.BooleanField(default=False)),
                ('usage_limit_total', models.IntegerField(blank=True, null=True)),
                ('usage_limit_per_user', models.IntegerField(blank=True, null=True)),
                ('current_usage_count', models.IntegerField(default=0)),
                ('starts_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='coupon_redemptions',
            fields=[
                ('id', models.CharField(default=apps.core.models.generate_id, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('discount_retained', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_redemptions', to='identity.user_profiles')),
                ('coupon_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='coupons.coupons')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
