# Generated by Django 6.0.6 on 2026-07-07 07:12

import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.CharField(default=apps.core.models.generate_id, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_number', models.CharField(max_length=20)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('order_status', models.CharField(choices=[('waiting_for_payment', 'Waiting for payment'), ('placed', 'Order Confirmed'), ('cancelled', 'cancelled'), ('picked_up', 'Order Picked up'), ('in_transit', 'Order in Transit'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered'), ('attempted_delivery', 'Attempted delivery'), ('return', 'Return (RTO)')], max_length=50)),
                ('payment_method', models.CharField(choices=[('cash_on_delivery', 'Cash on delivery (COD)'), ('pre_paid', 'Pre Paid'), ('partially_paid', 'Partially Paid'), ('refunded', 'Refunded')], max_length=50)),
                ('items_subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_international', models.BooleanField(default=False)),
                ('shipping_snapshot', models.JSONField()),
                ('shipping_charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other_charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idempotency_token', models.CharField(max_length=100, unique=True)),
                ('courier_name', models.CharField(max_length=50)),
                ('courier_id', models.CharField(max_length=50)),
                ('tracking_number', models.CharField(max_length=50, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity.user_profiles')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='order_items',
            fields=[
                ('id', models.CharField(default=apps.core.models.generate_id, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item_image_id', models.CharField(max_length=20)),
                ('item_name', models.CharField(max_length=50)),
                ('item_sku', models.CharField(max_length=20)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hsn_code', models.CharField(max_length=15)),
                ('tax_rate', models.CharField(max_length=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('variant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='catalog.product_variants')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='checkout.orders')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='payment_transactions',
            fields=[
                ('id', models.CharField(default=apps.core.models.generate_id, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gateway_provider', models.CharField()),
                ('gateway_transaction_id', models.CharField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('card', 'card'), ('netbanking', 'netbanking'), ('wallet', 'wallet'), ('emi', 'emi'), ('upi', 'upi'), ('other', 'other')], max_length=50)),
                ('payment_status', models.CharField(choices=[('created', 'created'), ('authorized', 'authorized'), ('captured', 'captured'), ('refunded', 'refunded'), ('failed', 'failed'), ('canceled', 'canceled')], max_length=50)),
                ('cryptographic_signature', models.CharField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='checkout.orders')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity.user_profiles')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='shopping_carts',
            fields=[
                ('id', models.CharField(default=apps.core.models.generate_id, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session_token', models.CharField(blank=True, max_length=256, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='identity.user_profiles')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='shopping_carts_items',
            fields=[
                ('id', models.CharField(default=apps.core.models.generate_id, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField(default=0)),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts_items', to='checkout.shopping_carts')),
                ('variant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product_variants')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
