# Generated by Django 6.0.6 on 2026-07-07 07:12

import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('checkout', '0001_initial'),
        ('identity', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='return_requests',
            fields=[
                ('id', models.CharField(default=apps.core.models.generate_id, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('return_number', models.CharField(max_length=20)),
                ('requested_method', models.CharField(choices=[('return', 'Return'), ('partial_return', 'Partial Return'), ('replacement', 'Replacement'), ('refund', 'Refund')], max_length=50)),
                ('request_status', models.CharField(choices=[('requested', 'Requested'), ('processing', 'Processing'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], max_length=50)),
                ('return_reason', models.CharField(max_length=80)),
                ('settlement_methods', models.CharField(choices=[('return', 'Return'), ('partial_return', 'Partial Return'), ('replacement', 'Replacement'), ('refund', 'Refund')], max_length=50)),
                ('settlement_date', models.DateField()),
                ('transaction_reference', models.CharField(max_length=50)),
                ('customer_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eligible_refund', models.DecimalField(decimal_places=2, max_digits=10)),
                ('refund_total', models.CharField(max_length=50)),
                ('refund_transaction_id', models.CharField(max_length=50)),
                ('is_deleted', models.BooleanField(default=False)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.orders')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity.user_profiles')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='return_items',
            fields=[
                ('id', models.CharField(default=apps.core.models.generate_id, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item_quantity', models.PositiveIntegerField(default=0)),
                ('item_condition', models.CharField(max_length=50)),
                ('customer_proof_images', models.FileField(upload_to='returns/user_uploads/')),
                ('serial_number', models.CharField(blank=True, max_length=80, null=True)),
                ('is_inspected', models.BooleanField(default=False)),
                ('restockable', models.BooleanField(default=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.orders')),
                ('variant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product_variants')),
                ('return_request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rms.return_requests')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='return_shipment',
            fields=[
                ('id', models.CharField(default=apps.core.models.generate_id, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipping_carrier', models.CharField(max_length=50)),
                ('tracking_number', models.CharField(max_length=50)),
                ('label_url', models.CharField()),
                ('label_created_at', models.DateField()),
                ('shipment_status', models.CharField(max_length=50)),
                ('return_charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('package_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.packages')),
                ('return_request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='rms.return_requests')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
