# Generated by Django 6.0.6 on 2026-07-07 07:12

import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_profiles',
            fields=[
                ('id', models.CharField(default=apps.core.models.generate_id, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=256)),
                ('first_name', models.CharField(blank=True, max_length=40)),
                ('last_name', models.CharField(blank=True, max_length=40)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('auth_provider', models.CharField(blank=True, max_length=50, null=True)),
                ('auth_provider_uid', models.CharField(blank=True, max_length=255, null=True)),
                ('is_gstin', models.BooleanField(default=False)),
                ('gstin', models.CharField(blank=True, max_length=15, null=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='user_otp_verifications',
            fields=[
                ('id', models.CharField(default=apps.core.models.generate_id, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('identifier', models.CharField(max_length=255)),
                ('otp_hash', models.CharField(max_length=10)),
                ('purpose', models.CharField(choices=[('email_verification', 'Email Verification'), ('phone_verification', 'Phone Verification'), ('password_reset', 'Password Reset')], max_length=50)),
                ('attempt_count', models.IntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_verifications', to='identity.user_profiles')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='user_address',
            fields=[
                ('id', models.CharField(default=apps.core.models.generate_id, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient_name', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(max_length=15)),
                ('address_type', models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('other', 'Other')], max_length=50)),
                ('is_default', models.BooleanField(default=False)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='identity.user_profiles')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='security_login_logs',
            fields=[
                ('id', models.CharField(default=apps.core.models.generate_id, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('attempted_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('successful', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_logs', to='identity.user_profiles')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='refresh_tokens',
            fields=[
                ('id', models.CharField(default=apps.core.models.generate_id, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('token_hash', models.CharField(max_length=255, unique=True)),
                ('previous_token_hash', models.CharField(max_length=255)),
                ('device_info', models.CharField(blank=True, max_length=255, null=True)),
                ('is_revoked', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to='identity.user_profiles')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
